name: Test

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}
    steps:
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: 'HITSZ-OpenAuto/AUTO3002A'
          ref: 'main'
          path: "."
          ext: ".pdf"
  test:
    needs: list-files
    runs-on: ubuntu-latest
    steps:
      - name: Save Paths to File
        run: |
          echo "${{ needs.list-files.outputs.paths }}" > output.txt
      - name: Output File Content
        run: cat output.txt